setup
setUp
	zero := 0 asArbitraryPrecisionFloatNumBits: Float precision.
	one := 1 asArbitraryPrecisionFloatNumBits: Float precision.
	two := 2 asArbitraryPrecisionFloatNumBits: Float precision.
	half := 1/2 asArbitraryPrecisionFloatNumBits: Float precision.
	minusOne := -1 asArbitraryPrecisionFloatNumBits: Float precision.
	minusTwo := -2 asArbitraryPrecisionFloatNumBits: Float precision.
	huge := (10 raisedTo: 100) asArbitraryPrecisionFloatNumBits: Float precision.